Repository teamcors/teamcors.github.io, pull requests merged in 2024-03, with the labels that each got.

#7 [~3/4] 팀 블로그 기초 공사 3
  src/components/global-styles.js
  src/components/header.js
Labels: 🛠feature

#10 [~3/10] 코테 스터디 2주차 회고록 작성
  content/posts/problem_solving/study-week2-bfs-dfs-chaeeun-han.md
  content/posts/problem_solving/study-week2-bfs-dfs-hyojeongchoi.md
  content/posts/problem_solving/study-week2-bfs-dfs-nusuy.md
  content/posts/problem_solving/study-week2-bfs-dfs-queue-ri.md
Labels: ✍docs

#12 [~3/11] 7/19-7/26 금주의 토픽 포스팅
  content/posts/weddings-are-basically-funerals-with-cake.md
  content/posts/weekly_topic/elk.md
  content/posts/weekly_topic/grafana.md
  content/posts/weekly_topic/scale-up-scale-out.md
  static/media/L4-L7.png
  static/media/L4.jpg
  static/media/L7.jpg
  static/media/cpu-sdd.png
  static/media/df-scale-up-scale-out.png
  static/media/scale-out.png
  static/media/scale-up.png
  static/media/tomcat_access.jpeg
Labels: ✍docs

#13 [~3/13] 팀블로그 기초공사2
  content/pages/about.md
  content/pages/index.md
  src/components/global-styles.js
  src/templates/about-template.js
  src/templates/index-template.js
  src/templates/post-template.js
  static/media/profile-medium-dark.png
  static/media/profile-medium-light.png
Labels: ✍docs, 🛠feature

#15 [~3/12] 포스트 썸네일 영역 추가
  content/posts/do-you-know-anything-about-sensory-deprivation-tanks.md
  content/posts/friends-dont-lie.md
  content/posts/magnificent-desolation.md
  content/posts/mornings-are-for-coffee-and-contemplation.md
  content/posts/nobody-exists-on-purpose.md
  content/posts/nobody-normal-ever-accomplished-anything-meaningful-in-this-world.md
  content/posts/one-world.md
  content/posts/pale-blue-dot.md
  content/posts/she-shut-one-door-with-her-mind.md
  content/posts/symbol-of-apollo.md
  content/posts/this-is-not-yours-to-fix-alone.md
  content/posts/tough-and-competent.md
  content/posts/we-choose-to-go-to-the-moon.md
  content/posts/weekly_topic/elk.md
  content/posts/weekly_topic/grafana.md
  content/posts/weekly_topic/scale-up-scale-out.md
  content/posts/why-are-you-fighting-cant-you-see-youre-all-the-same.md
  content/posts/why-do-we-even-need-weapons-anyway.md
  content/posts/why-would-a-pop-tart-want-to-live-inside-a-toaster.md
  content/posts/you-shouldnt-like-things-because-people-tell-you-youre-supposed-to.md
  content/posts/youre-pretty-cute-you-know-that.md
  src/components/post-list.js
  src/pages/blog.js
  src/templates/index-template.js
Labels: 🛠feature
